### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by jzarca01** [lramsey/product-recommender#2]
Hi lramsey,
First of all thanks for your hard work

Every time i try to launch product-demo using node index.js i get an error

```
begin analysis
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at _buildRecVariables (/home/pi/product/product-recommender/node_modules/product-recommender/node/engine.js:31:22)
    at Socket.<anonymous> (/home/pi/product/product-recommender/node_modules/product-recommender/node/engine.js:24:5)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
```

**Comment by mrudula93** [comment]
Hi Iramsey,

I am facing the same issue as well. Can you please tell us how to resolve this issue? 

Thank you!
